/* 교과서 실험 — 교과서 탐구를 시뮬레이션으로 해 보고 하나만 바꿔 내 탐구로. 엔진: ../assets/inquiry.js
   교과서 쪽 번호는 비상교육 교과서. 내용은 교과서 문장을 옮기지 않고 짧게 줄여 새로 썼다. */
window.sthInquiry({ mount: "inq", key: "inq", result: "rInq", items: [
  { id: "e1", book: "행성우주과학", page: 93, title: "색등급도로 성단의 나이 비교하기", purpose: "두 산개 성단의 색등급도에서 전향점 위치를 견주어 어느 성단이 더 늙었는지 판단한다.",
    steps: ["각 성단의 색등급도에서 주계열을 찾는다", "주계열에서 별들이 꺾여 나가는 전향점을 찾는다", "두 성단의 전향점 위치를 견준다", "어느 성단이 더 늙었는지 판단한다"],
    iv: "성단의 종류", dv: "전향점의 색지수(온도)·등급", cv: ["같은 축의 색등급도"], safety: "",
    extend: ["성단을 하나 더 골라 전향점 온도 순서와 나이 순서가 맞는지 확인하기", "전향점 대신 가장 밝은 주계열 별의 등급으로 견주어도 같은 순서가 나올까"],
    sim: { kind: "iframe", name: "NAAP 성단 HR도 맞추기(영어)", url: "https://astro.unl.edu/naap/distance/animations/clusterFittingExplorer.html", h: 600,
      ivControl: "'Cluster Selection' 목록에서 성단 바꾸기(목록이 마우스로 안 열리면 누른 뒤 ↓ 키)",
      dvReading: "HR도에서 성단 별들이 주계열에서 꺾여 나가는 전향점의 온도(K)·등급(가로축이 색지수가 아니라 온도)",
      x: { label: "성단 이름" }, y: { label: "전향점 온도", unit: "K" } } },
  { id: "e2", book: "행성우주과학", page: 94, title: "주계열 맞추기로 성단까지 거리 구하기", purpose: "성단 별들의 색등급도를 표준 주계열과 견주어 거리 지수와 거리를 구한다.",
    steps: ["성단 자료를 그래프에 찍어 색등급도를 만든다", "성단의 주계열을 찾는다", "같은 색지수에서 표준 주계열과의 위아래 등급 차를 읽는다", "거리 지수 식으로 성단까지 거리를 계산한다"],
    iv: "성단의 종류", dv: "거리 지수 m−M(등급), 성단까지 거리(pc)", cv: ["같은 색지수에서 위아래 등급 차 비교"], safety: "",
    extend: ["다른 성단을 맞춰 거리 지수가 1 커질 때 거리가 몇 배가 되는지 확인하기", "주계열을 일부러 0.5 등급 어긋나게 맞추면 거리가 얼마나 달라질까"],
    sim: { kind: "iframe", name: "NAAP 성단 HR도 맞추기(영어)", url: "https://astro.unl.edu/naap/distance/animations/clusterFittingExplorer.html", h: 600,
      ivControl: "성단을 고른 뒤 HR도 위 성단 자료를 위아래로 끌어 표준 주계열(빨간 선)에 맞추기",
      dvReading: "왼쪽 절대 등급 M 과 오른쪽 겉보기 등급 m 눈금 차이, 'Distance Modulus Calculator'에 넣어 얻은 거리 d",
      x: { label: "거리 지수 m−M", unit: "등급" }, y: { label: "성단까지 거리", unit: "pc" } } },
  { id: "e3", book: "행성우주과학", page: 98, title: "세페이드 변광성으로 구상 성단 거리 구하기", purpose: "세페이드 변광성의 주기-광도 관계로 구상 성단까지 거리를 구하고 우리은하 중심의 위치를 추정한다.",
    steps: ["세페이드 변광성의 주기로 절대 등급을 읽는다", "겉보기 등급과 거리 지수로 구상 성단(M3)까지 거리를 구한다", "모둠원이 좌표 평면을 나눠 구상 성단들을 찍는다", "분포의 중심을 표시해 태양에서 은하 중심까지 거리를 구하고 은하 크기를 추정한다"],
    iv: "세페이드 변광성의 변광 주기(일)", dv: "구상 성단까지 거리(kpc)", cv: ["같은 주기-광도 관계", "같은 좌표계·축척"], safety: "",
    extend: ["겉보기 등급이 같은데 주기만 긴 세페이드라면 더 멀리 있을까", "성간 소광만 1 등급 넣으면 구한 거리가 얼마나 줄어들까", "주기는 그대로 두고 겉보기 등급만 1 등급 어둡게 하면 거리는 몇 배가 될까"],
    sim: { kind: "model", name: "가상 세페이드 거리 재기", noise: 0.02,
      note: "고전 세페이드의 주기-광도 관계 M = −2.43(log P − 1) − 4.05 (안시 절대 등급)와 거리 지수 m − M − A = 5 log d − 5 (d 는 pc, A 는 성간 소광)로 셉니다. 구상 성단의 변광성은 이보다 어두운 종류일 수 있어 교과서 그래프 값과 조금 다를 수 있습니다. 성단 좌표를 찍어 중심을 찾는 부분은 종이에서 하세요.",
      inputs: [{ k: "P", label: "변광 주기", unit: "일", min: 1, max: 50, step: 0.5, value: 10 },
               { k: "m", label: "평균 겉보기 등급", unit: "등급", min: 8, max: 20, step: 0.1, value: 13 },
               { k: "A", label: "성간 소광", unit: "등급", min: 0, max: 2, step: 0.1, value: 0 }],
      outputs: [{ k: "M", label: "절대 등급", unit: "등급", dp: 2, expr: "-2.43*(Math.log(P)/Math.LN10-1)-4.05" },
                { k: "d", label: "거리", unit: "kpc", dp: 2, expr: "Math.pow(10,(m-A-(-2.43*(Math.log(P)/Math.LN10-1)-4.05)+5)/5)/1000" }] } },
  { id: "e4", book: "행성우주과학", page: 105, title: "관측 자료로 성간 티끌의 존재 추론하기", purpose: "같은 하늘 영역의 가시광선·근적외선 사진을 견주어 성간 티끌이 빛을 가리는 효과를 추론한다.",
    steps: ["같은 영역을 가시광선과 근적외선으로 찍은 사진을 나란히 놓는다", "근적외선에서만 보이는 별을 찾는다", "두 사진의 차이로 성간 티끌의 존재와 성질을 추론한다"],
    iv: "관측 파장(가시광선·근적외선)", dv: "보이는 별의 수·밝기", cv: ["같은 하늘 영역", "같은 시야 크기"], safety: "",
    extend: ["티끌이 없는 다른 영역에서도 두 파장의 별 수 차이가 클까", "근적외선 J 와 K 처럼 파장만 더 길게 바꾸면 보이는 별 수가 더 늘까"],
    sim: { kind: "iframe", name: "Aladin Lite(CDS 전천 영상)", url: "https://aladin.cds.unistra.fr/AladinLite/?target=Barnard%2068", h: 600,
      ivControl: "'Surveys' 목록에서 DSS2(가시광선) ↔ 2MASS(근적외선) 바꾸기, Target 칸에 같은 영역(예: Barnard 68) 넣기",
      dvReading: "같은 시야 안에서 보이는 별의 수(가운데 어두운 구름 안쪽을 세기)",
      x: { label: "관측 파장(가시광선 / 근적외선)" }, y: { label: "구름 안에 보이는 별", unit: "개" } } },
  { id: "e5", book: "행성우주과학", page: 109, title: "은하의 회전 속도 곡선 분석하기", purpose: "보이는 물질만으로 기대되는 회전 속도와 실제 회전 속도를 견주어 암흑 물질이 있는지 추정한다.",
    steps: ["모둠별로 세 은하의 회전 속도 곡선 특징을 정리한다", "중심에서 20 kpc 인 곳의 실제 속도와 보이는 물질만의 속도를 제곱해 견준다", "그 차이를 설명할 수 있는 은하의 구성 요소를 찾는다", "세 은하의 공통점을 정리한다"],
    iv: "은하 중심으로부터의 거리(kpc)", dv: "회전 속도(km/s)", cv: ["같은 은하", "같은 거리(20 kpc)에서 비교"], safety: "",
    extend: ["암흑 물질 헤일로를 빼면 먼 곳의 회전 속도는 어떻게 될까", "원반 질량만 바꾸면 20 kpc 에서의 회전 속도가 얼마나 달라질까"],
    sim: { kind: "model", name: "가상 나선 은하", noise: 0.02,
      note: "원운동 v = √(G·M(r)/r), M(r) 은 반지름 r 안의 질량. 팽대부 1×10¹⁰ 태양 질량(축척 0.5 kpc), 원반은 축척 길이 3 kpc 인 지수 원반을 공 모양으로 근사, 암흑 물질 헤일로는 중심핵 5 kpc 인 등온 공(바깥 속도 150·200 km/s)으로 둡니다. G = 4.30×10⁻⁶ kpc·(km/s)²/태양 질량.",
      inputs: [{ k: "r", label: "은하 중심으로부터 거리", unit: "kpc", min: 1, max: 30, step: 1, value: 20 },
               { k: "Md", label: "원반 질량", unit: "×10¹⁰ 태양 질량", min: 1, max: 10, step: 0.5, value: 6 }],
      choices: [{ k: "vh", label: "암흑 물질 헤일로", opts: [["없음", 0], ["있음(보통)", 150], ["있음(많음)", 200]], value: 200 }],
      outputs: [{ k: "v", label: "회전 속도(관측)", unit: "km/s", dp: 0, expr: "(function(){var G=4.30e-6,Mb=1e10*Math.pow(r,3)/Math.pow(r*r+0.25,1.5),Mdisk=Md*1e10*(1-(1+r/3)*Math.exp(-r/3)),vis=G*(Mb+Mdisk)/r,h=vh*vh*(1-(5/r)*Math.atan(r/5));return Math.sqrt(vis+h);})()" },
                { k: "vv", label: "보이는 물질만으로 기대되는 속도", unit: "km/s", dp: 0, expr: "(function(){var G=4.30e-6,Mb=1e10*Math.pow(r,3)/Math.pow(r*r+0.25,1.5),Mdisk=Md*1e10*(1-(1+r/3)*Math.exp(-r/3));return Math.sqrt(G*(Mb+Mdisk)/r);})()" }] } },
  { id: "e6", book: "행성우주과학", page: 113, title: "은하 스펙트럼의 적색 이동으로 거리 추정하기", purpose: "스펙트럼선이 옮겨 간 정도로 은하의 후퇴 속도를 구하고 허블-르메트르 법칙으로 거리를 구한다.",
    steps: ["은하 스펙트럼에서 기준 파장과 관측 파장을 읽는다", "파장 차이로 적색 이동 z 와 후퇴 속도를 구한다", "허블 상수로 은하까지 거리를 구한다"],
    iv: "은하까지 거리(Mpc)", dv: "스펙트럼선의 파장 이동량(nm)", cv: ["같은 기준 파장선", "같은 허블 상수"], safety: "",
    extend: ["같은 은하를 다른 스펙트럼선으로 보면 파장 이동량이 같을까, 적색 이동 z 는 같을까", "허블 상수만 바꾸면 같은 거리 은하의 파장 이동량은 어떻게 될까"],
    sim: { kind: "model", name: "가상 은하 분광", noise: 0.02,
      note: "허블-르메트르 법칙 v = H₀·d 와 가까운 은하의 도플러 근사 z = Δλ/λ₀ = v/c (c = 3.0×10⁵ km/s, z 가 0.1보다 작을 때 맞음). 은하 자체의 고유 운동은 없다고 봅니다. 잰 이동량으로 z, v, d 를 거꾸로 계산해 처음 정한 거리와 견주세요.",
      inputs: [{ k: "D", label: "은하까지 거리", unit: "Mpc", min: 5, max: 400, step: 5, value: 100 },
               { k: "H", label: "허블 상수", unit: "km/s/Mpc", min: 60, max: 80, step: 1, value: 70 }],
      choices: [{ k: "L0", label: "기준 스펙트럼선", opts: [["수소 Hα 656.3 nm", 656.3], ["수소 Hβ 486.1 nm", 486.1], ["칼슘 K 393.4 nm", 393.4], ["칼슘 H 396.8 nm", 396.8]], value: 656.3 }],
      outputs: [{ k: "dl", label: "파장 이동량 Δλ", unit: "nm", dp: 2, expr: "L0*H*D/3.0e5" }] } }
] });
